token=""

quron="https://t.me/barcha_kitoblar_uz/8"
navoiy="\nHayrat-ul Abror\n https://t.me/barcha_kitoblar_uz/21\nFarhod va shirin\n https://t.me/barcha_kitoblar_uz/23\n\n \nLayli va Majnun\n https://t.me/barcha_kitoblar_uz/20\nSabbai Sayyor\n https://t.me/barcha_kitoblar_uz/22\nSaddi Iskandariy\n https://t.me/barcha_kitoblar_uz/24"
termiziy="\nHadislar\n https://t.me/barcha_kitoblar_uz/27"
buxoriy="\nal-jome as-sahih\nhttps://t.me/barcha_kitoblar_uz/26 "
navaviy="https://t.me/barcha_kitoblar_uz/10"
imomhanifa="https://t.me/barcha_kitoblar_uz/47"
python="\nO'zbekcha qo'llanma\nhttps://t.me/barcha_kitoblar_uz/12 "
javascript="\nQollanma\nhttps://t.me/barcha_kitoblar_uz/33 "
html_css="\nHtml\n https://t.me/barcha_kitoblar_uz/31 \nCss\nhttps://t.me/barcha_kitoblar_uz/32 "
django="\nDjango web\nhttps://t.me/barcha_kitoblar_uz/11 "
abfizika="\nTematika\n https://t.me/barcha_kitoblar_uz/45\nQo'llanma\nhttps://t.me/barcha_kitoblar_uz/46"
abmatem="\nTematika\n https://t.me/barcha_kitoblar_uz/28\nYakkabog'\n https://t.me/barcha_kitoblar_uz/30"
bookeng="\nKitobi\n https://t.me/barcha_kitoblar_uz/34 \nAudiosi\n https://t.me/barcha_kitoblar_uz/35"
bookrus="\nKitobi\nhttps://t.me/barcha_kitoblar_uz/42 \nAudiosi\n https://t.me/barcha_kitoblar_uz/42"
koreys="\nKitobi\nhttps://t.me/barcha_kitoblar_uz/41 \nAudiosi\n https://t.me/barcha_kitoblar_uz/41"
kornegi="\nMuomala sirlari\n https://t.me/barcha_kitoblar_uz/9\nNotiqlik Sanati\nhttps://t.me/barcha_kitoblar_uz/15 \nIMkonni boy bermang\n https://t.me/barcha_kitoblar_uz/16"
kiosaki="https://t.me/barcha_kitoblar_uz/17"
uolter="https://t.me/barcha_kitoblar_uz/48"
bizness="https://t.me/barcha_kitoblar_uz/19"

chingiz="https://t.me/barcha_kitoblar_uz/18"


